name: Formatter
on:
  push:
    branches:
    - 'feature/**'
  pull_request:
    branches:
    - 'feature/**'

jobs:
  Formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      - name: Setup Node.js Environment
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Run Laravel Pint
        id: run_pint
        run: |
          if ! vendor/bin/pint --test; then
            echo "Laravel Pint found formatting issues in the following files:"
            vendor/bin/pint --test | grep -E "^[^ ]+\.php"
            exit 1
          fi
