name: Formatter
on:
  push:
    branches:
    - 'feature/**'
  pull_request:
    branches:
    - 'feature/**'
jobs:
  Formatter:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Setup PHP Environment
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.2"
      - uses: actions/checkout@v3
      - name: Setup PHP Environment
        uses: actions/setup-node@v3
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm install

      - name: Format
        run: |
          vendor/bin/pint
          npx prettier --write resources/js/**/*.{js,jsx}
          npx prettier --write resources/css/**/*.css
          npx blade-formatter --write resources/views/**/*.blade.php
          npx blade-formatter --write resources/views/*.blade.php

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Formatted
          skip_fetch: true
